version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  app:
    depends_on:
        - db
    build: .
    container_name: app
    volumes:
      - .:/code
    ports:
      - 8000:8000
    restart: always

volumes:
  pgdata:
