# Generated by Django 4.2 on 2023-04-09 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('users', models.ManyToManyField(related_name='tasks', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
